Search: Fixes the spacing issue between suggested artworks (AIC-633)
art-institute-of-chicago/aic-mobile-android pull request #352
Opened 2018-11-20 21:11 UTC by sam33rdhakal

The cause behind this issue was the logic we used to get column number for suggested artworks. That logic was based on the position of the `on the map` cell.

```
val columnValue = (currentPosition - onTheMapPosition) % maxSize
```

This logic can go wrong when suggested artwork cells are recycled before that `on the map` cell. So the proposed solution is to not use `on the map` cell at all. Now I pass the order of the cells when they are constructed and then use it to calculate the column index. 

```
val columnValue = viewModel.order % maxSize
```

2018-11-20 21:36 UTC, Cliabhach requested changes
One comment; everything else looks great.

2018-11-20 21:36 UTC, Cliabhach commented on search/src/main/java/edu/artic/search/SearchResultCellViewModels.kt
> +                                  override val order: Int = -1) : SearchBaseCellViewModel(), OrderedCellViewModel {
I think we can remove the default value for `order` here. That way the compiler will error out if we forget to include a number.

2018-11-20 21:45 UTC, Cliabhach approved these changes
Great! Let's get this in.

2026-04-22 17:00 UTC, nikhiltri approved these changes
Good fix. ⭐

2026-05-20 00:52 UTC, closed without merging